# Generated by scripts/generate-dockerfile.py. Do not edit manually.
FROM node:24.18-alpine3.23 AS source
RUN apk add --no-cache git
WORKDIR /source
RUN git init . && git remote add origin https://github.com/bluesky-social/atproto.git \
 && git fetch --depth=1 origin refs/tags/@atproto/pds@0.5.34 \
 && git checkout --detach FETCH_HEAD \
 && test "$(git rev-parse HEAD)" = "7ca16cc6989f8247637615aca17c5abb911b8fb1"
COPY patches /patches
COPY examples/branding-smoke /examples/branding-smoke
COPY scripts/apply-patches.sh /apply-patches.sh
ARG PATCH_PROFILE=production
RUN sh /apply-patches.sh "$PATCH_PROFILE"

# NOTE there is an additional build stage below that should match
FROM node:24.18-alpine3.23 AS build

RUN npm install -g pnpm@11.11.0

WORKDIR /app

COPY --from=source /source/.npmrc ./
COPY --from=source /source/.nvmrc ./
COPY --from=source /source/package.json ./
COPY --from=source /source/pnpm-lock.yaml ./
COPY --from=source /source/pnpm-workspace.yaml ./
COPY --from=source /source/tsconfig ./tsconfig
COPY --from=source /source/lexicons ./lexicons

# bsync is not a runtime dep but bsky's "codegen:buf" script reads ../bsync/proto at build time
COPY --from=source /source/packages/bsync/proto ./packages/bsync/proto

# NOTE pds's transitive dependencies go here: if that changes, this needs to be updated.
# pnpm list --filter 'pds-service...' --depth 0 --json | jq '.[].path' | sort -u | sed "s|\"$PWD/|./|; s|\"\$||"
COPY --from=source /source/packages/api ./packages/api
COPY --from=source /source/packages/aws ./packages/aws
COPY --from=source /source/packages/common-web ./packages/common-web
COPY --from=source /source/packages/common ./packages/common
COPY --from=source /source/packages/crypto ./packages/crypto
COPY --from=source /source/packages/did ./packages/did
COPY --from=source /source/packages/identity ./packages/identity
COPY --from=source /source/packages/internal/did-resolver ./packages/internal/did-resolver
COPY --from=source /source/packages/internal/fetch-node ./packages/internal/fetch-node
COPY --from=source /source/packages/internal/fetch ./packages/internal/fetch
COPY --from=source /source/packages/internal/handle-resolver ./packages/internal/handle-resolver
COPY --from=source /source/packages/internal/identity-resolver ./packages/internal/identity-resolver
COPY --from=source /source/packages/internal/opentelemetry-node ./packages/internal/opentelemetry-node
COPY --from=source /source/packages/internal/pipe ./packages/internal/pipe
COPY --from=source /source/packages/internal/rolldown-plugin-bundle-manifest ./packages/internal/rolldown-plugin-bundle-manifest
COPY --from=source /source/packages/internal/simple-store-memory ./packages/internal/simple-store-memory
COPY --from=source /source/packages/internal/simple-store-redis ./packages/internal/simple-store-redis
COPY --from=source /source/packages/internal/simple-store ./packages/internal/simple-store
COPY --from=source /source/packages/internal/xrpc-utils ./packages/internal/xrpc-utils
COPY --from=source /source/packages/lex-cli ./packages/lex-cli
COPY --from=source /source/packages/lex/lex-builder ./packages/lex/lex-builder
COPY --from=source /source/packages/lex/lex-cbor ./packages/lex/lex-cbor
COPY --from=source /source/packages/lex/lex-client ./packages/lex/lex-client
COPY --from=source /source/packages/lex/lex-data ./packages/lex/lex-data
COPY --from=source /source/packages/lex/lex-document ./packages/lex/lex-document
COPY --from=source /source/packages/lex/lex-installer ./packages/lex/lex-installer
COPY --from=source /source/packages/lex/lex-json ./packages/lex/lex-json
COPY --from=source /source/packages/lex/lex-resolver ./packages/lex/lex-resolver
COPY --from=source /source/packages/lex/lex-schema ./packages/lex/lex-schema
COPY --from=source /source/packages/lex/lex ./packages/lex/lex
COPY --from=source /source/packages/lexicon ./packages/lexicon
COPY --from=source /source/packages/oauth/jwk-jose ./packages/oauth/jwk-jose
COPY --from=source /source/packages/oauth/jwk-webcrypto ./packages/oauth/jwk-webcrypto
COPY --from=source /source/packages/oauth/jwk ./packages/oauth/jwk
COPY --from=source /source/packages/oauth/oauth-client-browser-example ./packages/oauth/oauth-client-browser-example
COPY --from=source /source/packages/oauth/oauth-client-browser ./packages/oauth/oauth-client-browser
COPY --from=source /source/packages/oauth/oauth-client ./packages/oauth/oauth-client
COPY --from=source /source/packages/oauth/oauth-provider-api ./packages/oauth/oauth-provider-api
COPY --from=source /source/packages/oauth/oauth-provider-ui ./packages/oauth/oauth-provider-ui
COPY --from=source /source/packages/oauth/oauth-provider ./packages/oauth/oauth-provider
COPY --from=source /source/packages/oauth/oauth-scopes ./packages/oauth/oauth-scopes
COPY --from=source /source/packages/oauth/oauth-types ./packages/oauth/oauth-types
COPY --from=source /source/packages/pds ./packages/pds
COPY --from=source /source/packages/repo ./packages/repo
COPY --from=source /source/packages/syntax ./packages/syntax
COPY --from=source /source/packages/ws-client ./packages/ws-client
COPY --from=source /source/packages/xrpc-server ./packages/xrpc-server
COPY --from=source /source/packages/xrpc ./packages/xrpc
COPY --from=source /source/services/pds ./services/pds

# install all deps
RUN PUPPETEER_SKIP_DOWNLOAD=true pnpm install --frozen-lockfile
# build all the dependencies of ./package.json
RUN pnpm run --recursive --stream --workspace-concurrency 1 --filter 'pds-service...' build -- --force
RUN if test -f packages/oauth/oauth-provider/src/external/external-provider.test.ts; then cd packages/oauth/oauth-provider && pnpm test src/external src/router/create-external-middleware.test.ts src/account/account-manager.external.test.ts; fi
# install only prod deps, hoisted to root node_modules dir
RUN pnpm install --prod --shamefully-hoist --frozen-lockfile --prefer-offline --config.confirmModulesPurge=false

# Uses assets from build stage to reduce build size
FROM node:24.18-alpine3.23

RUN apk add --update dumb-init

# Avoid zombie processes, handle signal forwarding
ENTRYPOINT ["dumb-init", "--"]

COPY --from=build /app /app
WORKDIR /app/services/pds

RUN mkdir /app/data && chown node /app/data
VOLUME /app/data

EXPOSE 3000
ENV PDS_PORT=3000
ENV NODE_ENV=production
# potential perf issues w/ io_uring on this version of node
ENV UV_USE_IO_URING=0

# https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#non-root-user
USER node
CMD ["node", "--heapsnapshot-signal=SIGUSR2", "--enable-source-maps", "--import=@atproto/pds/telemetry", "index.ts"]

LABEL org.opencontainers.image.source=https://github.com/bluesky-social/atproto
LABEL org.opencontainers.image.description="ATP Personal Data Server (PDS)"
LABEL org.opencontainers.image.licenses=MIT

# Allows consumer to distinguish pre-otel builds
LABEL social.bsky.pds.telemetry="otel"
