#!/usr/bin/env python3
"""Preserve upstream build/runtime instructions; add immutable fetch + source patches."""
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent

def generate(pin, upstream):
    assert re.fullmatch(r"@atproto/pds@\d+\.\d+\.\d+", pin['tag'])
    assert re.fullmatch(r"[0-9a-f]{40}", pin['commit'])
    assert pin['repository'] == 'https://github.com/bluesky-social/atproto.git'
    base = re.search(r'^FROM (\S+) AS build$', upstream, re.M).group(1)
    preamble = f'''# Generated by scripts/generate-dockerfile.py. Do not edit manually.
FROM {base} AS source
RUN apk add --no-cache git
WORKDIR /source
RUN git init . && git remote add origin {pin['repository']} \\
 && git fetch --depth=1 origin refs/tags/{pin['tag']} \\
 && git checkout --detach FETCH_HEAD \\
 && test "$(git rev-parse HEAD)" = "{pin['commit']}"
COPY patches /patches
COPY examples/branding-smoke /examples/branding-smoke
COPY scripts/apply-patches.sh /apply-patches.sh
ARG PATCH_PROFILE=production
RUN sh /apply-patches.sh "$PATCH_PROFILE"

'''
    # Only replace build-context COPYs. Runtime COPY --from=build remains upstream.
    body = re.sub(r'^COPY (\./\S+) (.+)$',
                  lambda m: 'COPY --from=source /source/' + m[1][2:] + ' ' + m[2], upstream, flags=re.M)
    return preamble + body

if __name__ == '__main__':
    pin = json.loads((ROOT / 'upstream.json').read_text())
    (ROOT / 'Dockerfile').write_text(generate(pin, (ROOT / 'docs/upstream.Dockerfile').read_text()))
