#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# This section belongs to the procedure; the shared wizard library above is verbatim.
# The output is Docker raw env-file data, never shell code. Do not source it.
[[ -t 0 && -t 1 ]] || { printf 'Run this wizard in an interactive terminal.\n' >&2; exit 1; }
umask 077
ENV_FILE="${PDS_SETUP_FILE:-${HOME}/.config/linkjar-pds/setup.env}"
[[ "$ENV_FILE" = /* && ! -L "$ENV_FILE" ]] || { printf '%sUse an absolute, non-symlink PDS_SETUP_FILE.%s\n' "$RED" "$RESET" >&2; exit 1; }
mkdir -p "$(dirname "$ENV_FILE")"
if git -C "$(dirname "$ENV_FILE")" rev-parse --show-toplevel >/dev/null 2>&1; then
  warn 'Choose a private output directory outside every Git checkout.'
  exit 1
fi
[[ ! -e "$ENV_FILE" || -f "$ENV_FILE" ]] || exit 1
touch "$ENV_FILE"
chmod 600 "$ENV_FILE"

capture() {
  local key="$1" prompt="$2" secret="${3:-false}" pattern="${4:-.+}" value
  while true; do
    if [[ "$secret" = true ]]; then ask_secret "$key" "$prompt"; else ask "$key" "$prompt"; fi
    value="${!key}"
    if [[ "$value" != *$'\r'* && "$value" =~ $pattern ]]; then break; fi
    warn 'Value is missing or invalid; retry, or Ctrl-C to stop.'
  done
  write_env "$key" "$value"
}

require_done() { confirm "$1" || { warn 'Stopped; existing values are saved.'; exit 1; }; }

banner 'LinkJar PDS: collect provisioning inputs'
say "Output: $ENV_FILE (private Docker raw env-file; never source it)."
say 'No server is purchased, deployed, restarted or opened to traffic by this script.'
say 'Human dashboard changes happen only when you perform them.'
require_done 'Use this file for this environment?'

stage 'Host and DNS'
open_url 'https://console.hetzner.cloud/'
step 'Review #89: CX33, Nuremberg nbg1. Confirm current stock and total quote before purchasing.'
step 'Use your approved host; record its public IPv4. Install no service from this wizard.'
capture LINKJAR_HOST_IPV4 'Host IPv4:' false '^((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])$'
open_url 'https://dash.cloudflare.com/'
step 'Select linkjar.social → DNS → Records. Once the origin is ready, add proxied A records pds and * to that IPv4.'
step 'Add AAAA only if the host has working public IPv6. Use SSL/TLS Full (strict) after origin TLS is installed.'
step 'Keep app pages and cookies on linkjar.io; never place an app on linkjar.social.'
require_done 'Recorded the DNS plan and origin TLS prerequisites?'
write_env PDS_HOSTNAME 'pds.linkjar.social'
write_env PDS_SERVICE_HANDLE_DOMAINS '.linkjar.social'
write_env PDS_DATA_DIRECTORY '/app/data'
write_env PDS_PORT '3000'
write_env PDS_DEV_MODE 'false'
write_env PDS_RATE_LIMITS_ENABLED 'true'
write_env PDS_INVITE_REQUIRED 'false'

stage 'R2 blob storage'
open_url 'https://dash.cloudflare.com/?to=/:account/r2/overview'
step 'Choose the private PDS bucket. In Account Details → API Tokens → Manage, create a token with Object Read & Write scoped to that bucket.'
step 'Copy its S3 endpoint (use the jurisdiction-specific endpoint for an EU bucket), Access Key ID and Secret Access Key.'
capture PDS_BLOBSTORE_S3_BUCKET 'Bucket name:'
capture PDS_BLOBSTORE_S3_ENDPOINT 'Exact HTTPS S3 endpoint:' false '^https://[^/[:space:]]+$'
capture PDS_BLOBSTORE_S3_ACCESS_KEY_ID 'Access Key ID:' true
capture PDS_BLOBSTORE_S3_SECRET_ACCESS_KEY 'Secret Access Key:' true
write_env PDS_BLOBSTORE_S3_REGION 'auto'
write_env PDS_BLOBSTORE_S3_FORCE_PATH_STYLE 'true'
write_env PDS_BLOB_UPLOAD_LIMIT '52428800'
note 'Initial upload ceiling: 50 MiB. Confirm archive requirements before launch.'

stage 'Transactional mail and moderation'
open_url 'https://resend.com/domains'
step 'Use the existing waitlist sender service, Resend. Verify the sending domain and its displayed SPF/DKIM records.'
open_url 'https://resend.com/api-keys'
step 'Create a dedicated sending key for the verified domain. Build an SMTPS URL with username resend, port 465, and a percent-encoded API key as the password.'
step 'Format: smtps://resend:ENCODED_API_KEY@smtp.resend.com:465. Paste the complete URL below; entry is hidden.'
capture PDS_EMAIL_SMTP_URL 'SMTPS URL:' true '^smtps://[^[:space:]]+@smtp\.resend\.com:465$'
capture PDS_EMAIL_FROM_ADDRESS 'Verified sender (e.g. LinkJar <hello@updates.linkjar.io>):'
capture PDS_MODERATION_EMAIL_ADDRESS 'Monitored moderation mailbox:' false '^[^[:space:]@]+@[^[:space:]@]+$'
write_env PDS_MODERATION_EMAIL_SMTP_URL "$PDS_EMAIL_SMTP_URL"
require_done 'Verified the sender DNS records and assigned someone to monitor moderation mail?'

stage 'hCaptcha for open email signup'
open_url 'https://dashboard.hcaptcha.com/'
step 'Create or select a site key restricted to pds.linkjar.social; copy its site key and secret from the account dashboard.'
capture PDS_HCAPTCHA_SITE_KEY 'Site key:'
capture PDS_HCAPTCHA_SECRET_KEY 'Secret key:' true
if [[ -z "$(_existing PDS_HCAPTCHA_TOKEN_SALT || true)" ]]; then
  write_env PDS_HCAPTCHA_TOKEN_SALT "$(openssl rand -hex 32)"
fi
note 'D3 intentionally enables open signup. Keep rate limits and email hCaptcha; #99 governs the verified-provider exception.'

stage 'PDS secrets and PLC recovery custody'
open_url 'https://atproto.com/guides/going-to-production#plc-key-management'
step 'Use the approved secret store to create/store the online PDS secp256k1 rotation key. Paste only that online private key below.'
step 'Create and retain the higher-priority recovery private key offline. NEVER paste that private key here or copy it to the host.'
capture PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX 'Online PDS rotation private key (64 hex):' true '^[[:xdigit:]]{64}$'
capture PDS_RECOVERY_DID_KEY 'Offline recovery PUBLIC did:key:' false '^did:key:z[1-9A-HJ-NP-Za-km-z]+$'
capture LINKJAR_OFFLINE_RECOVERY_CUSTODY 'Recovery vault/item reference (no secret):'
for key in PDS_JWT_SECRET PDS_DPOP_SECRET PDS_ADMIN_PASSWORD; do
  if [[ -z "$(_existing "$key" || true)" ]]; then write_env "$key" "$(openssl rand -hex 32)"; fi
 done
require_done 'Verified the offline key is recoverable and separate from the online key?'

stage 'Apple registration'
open_url 'https://developer.apple.com/account/resources/identifiers/list'
step 'Enable Sign in with Apple on the primary app ID. Register a Services ID and associate it with that primary app.'
step 'Configure its web domain pds.linkjar.social and return URL https://pds.linkjar.social/oauth/external/apple/callback.'
open_url 'https://developer.apple.com/account/resources/authkeys/list'
step 'Create a Sign in with Apple key linked to the primary app. Download the .p8 once and store it in the operator vault; record its key ID there.'
step 'Generate the client-secret JWT with the protected key per Apple documentation. #99 consumes the signed JWT, not the private key.'
if confirm 'Store Apple credentials now?'; then
  capture PDS_EXTERNAL_APPLE_CLIENT_ID 'Services ID:'
  capture PDS_EXTERNAL_APPLE_CLIENT_SECRET 'Signed client-secret JWT:' true '^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$'
  capture LINKJAR_APPLE_SECRET_EXPIRES 'JWT expiry / rotation due date (YYYY-MM-DD):' false '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
  capture LINKJAR_APPLE_KEY_CUSTODY 'Apple .p8 vault/item reference (no key):'
else SKIPPED+=('Apple provider configuration; remains unavailable without both credentials'); fi

stage 'Google registration'
open_url 'https://console.cloud.google.com/auth/clients'
step 'Select the LinkJar project, complete Google Auth Platform branding/audience/data-access setup, then create a Web application client.'
step 'Add the exact authorized redirect URI https://pds.linkjar.social/oauth/external/google/callback. Use only openid, email and profile.'
step 'For testing, add the designated test users. Complete Google publication/verification requirements before public signup.'
if confirm 'Store Google credentials now?'; then
  capture PDS_EXTERNAL_GOOGLE_CLIENT_ID 'Client ID:'
  capture PDS_EXTERNAL_GOOGLE_CLIENT_SECRET 'Client secret:' true
else SKIPPED+=('Google provider configuration; remains unavailable without both credentials'); fi

stage 'GitHub registration'
open_url 'https://github.com/organizations/linkjar/settings/applications'
step 'Register a LinkJar-owned OAuth App: homepage https://linkjar.io, callback https://pds.linkjar.social/oauth/external/github/callback.'
step 'Use the organization settings OAuth Apps page. Generate a client secret; no repository or organization scope is needed.'
if confirm 'Store GitHub credentials now?'; then
  capture PDS_EXTERNAL_GITHUB_CLIENT_ID 'Client ID:'
  capture PDS_EXTERNAL_GITHUB_CLIENT_SECRET 'Client secret:' true
else SKIPPED+=('GitHub provider configuration; remains unavailable without both credentials'); fi

stage 'Telemetry and relay inventory'
open_url 'https://grafana.com/orgs'
step 'Open the existing Grafana stack and its OpenTelemetry connection instructions; copy the approved endpoint and authentication headers.'
if confirm 'Store telemetry settings now?'; then
  capture OTEL_EXPORTER_OTLP_ENDPOINT 'HTTPS OTLP endpoint:' false '^https://[^[:space:]]+$'
  capture OTEL_EXPORTER_OTLP_HEADERS 'OTLP headers (hidden):' true
else SKIPPED+=('Grafana OTLP configuration and uptime monitor'); fi
open_url 'https://atproto.com/guides/going-to-production#rate-limits'
step 'Record the intended relay URL(s), comma separated. Request crawl only after public health/identity checks pass; #92 owns the relay-cap request.'
capture PDS_CRAWLERS 'Relay HTTPS URL(s):' false '^https://[^[:space:]]+$'

stage 'Handoff for deployment and acceptance'
step 'Transfer the raw env file through the approved secret channel to /etc/linkjar-pds/staging.env, mode 0600. Never commit or source it.'
step 'Use staging/compose.yml with Docker Compose 2.30+ and the verified GHCR digest. Keep port 3000 on loopback behind Caddy.'
step 'Complete docs/runbooks/pds.md: TLS, firewall, key/backups restore, R2 roundtrip, mail, hCaptcha, PLC account, handle and OAuth checks.'
SKIPPED+=('Host provisioning, origin TLS, service deployment and every live acceptance check in #90')
SKIPPED+=('Provider #99 must be merged and configured before Apple/Google/GitHub routes are available')
require_done 'Inputs saved and remaining deployment checks understood?'
finish
say 'Input collection complete. This is not a deployment or acceptance result.'
