//! Generates `crates/pds-types/src/generated/mod.rs` from the lexicon corpus.
//!
//! Layout: one nested module per NSID segment (`com::atproto::repo::create_record`).
//! Per definition:
//! - `record`: a struct named after the NSID's last segment, plus `NSID`.
//! - `query` and `procedure`: `Params`, `Input`, `Output` and `ERRORS`.
//! - `subscription`: `Params`, `Message` (a union) and `ERRORS`.
//! - `object`: a struct named after the definition.
//! - `union`: an enum tagged by `$type`, open unions get an `Other(Data)` variant.
//! - `token`: a string constant with the token's full name.
//! - primitives and arrays: type aliases.
//! - `permission-set` and `permission`: a constant naming the set; they are
//!   consumed at runtime by pds-lexicon, not as API types.
//!
//! Field names are converted to snake_case with a serde rename back to the
//! lexicon spelling. Optional fields are `Option<T>` and skipped when absent;
//! nullable fields are `Option<T>` and written as null. Inline objects and
//! unions get names from their parent type and field.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use anyhow::{Context, Result, bail};
use heck::{ToPascalCase, ToSnakeCase};
use pds_lexicon::Corpus;
use pds_lexicon::model::{
    LexArray, LexObject, LexObjectOrRef, LexPrimitiveOrArray, LexRefUnion, LexRefUnionOrUnion,
    LexString, LexType, LexUserType, LexXrpcBody, LexXrpcError, LexXrpcParameters,
};

const RUST_KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn", "for",
    "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
    "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use", "where",
    "while", "async", "await", "dyn", "abstract", "become", "box", "do", "final", "macro",
    "override", "priv", "typeof", "unsized", "virtual", "yield", "try", "gen",
];

/// Generates the whole file as a string.
pub fn generate(corpus: &Corpus) -> Result<String> {
    let mut tree = ModTree::default();
    for doc in corpus.docs() {
        let segments: Vec<&str> = doc.id.split('.').collect();
        let mut reserved: BTreeSet<String> = ["Params", "Input", "Output", "Message"]
            .iter()
            .map(|s| (*s).to_owned())
            .collect();
        reserved.extend(
            doc.defs
                .keys()
                .map(|k| type_name_for_def(corpus, &doc.id, k)),
        );
        let mut emitter = Emitter {
            corpus,
            doc_id: &doc.id,
            out: String::new(),
            inline_names: reserved,
        };
        emitter.doc(doc)?;
        tree.insert(&segments, emitter.out);
    }
    let mut out = String::new();
    out.push_str("//! Generated by `cargo xtask codegen` from `lexicons/`. Do not edit.\n");
    out.push_str(
        "//! Types follow the lexicon definitions; see xtask/src/codegen.rs for the mapping.\n\n",
    );
    out.push_str("#![allow(unused_imports, dead_code)]\n\n");
    tree.render(&mut out, 0);
    Ok(out)
}

#[derive(Default)]
struct ModTree {
    children: BTreeMap<String, Self>,
    body: String,
}

impl ModTree {
    fn insert(&mut self, segments: &[&str], body: String) {
        if let Some((first, rest)) = segments.split_first() {
            let child = self.children.entry(module_name(first)).or_default();
            child.insert(rest, body);
        } else {
            self.body = body;
        }
    }

    fn render(&self, out: &mut String, depth: usize) {
        let indent = "    ".repeat(depth);
        if !self.body.is_empty() {
            for line in self.body.lines() {
                if line.is_empty() {
                    out.push('\n');
                } else {
                    out.push_str(&indent);
                    out.push_str(line);
                    out.push('\n');
                }
            }
        }
        for (name, child) in &self.children {
            let _ = writeln!(out, "{indent}pub mod {name} {{");
            child.render(out, depth + 1);
            let _ = writeln!(out, "{indent}}}");
        }
    }
}

fn module_name(segment: &str) -> String {
    let s = segment.to_snake_case();
    if RUST_KEYWORDS.contains(&s.as_str()) {
        format!("r#{s}")
    } else {
        s
    }
}

fn field_name(name: &str) -> (String, bool) {
    let s = name.to_snake_case();
    if RUST_KEYWORDS.contains(&s.as_str()) {
        (format!("r#{s}"), true)
    } else {
        (s.clone(), s != name)
    }
}

/// The Rust type name of a definition. `main` takes the NSID's last segment
/// unless another definition in the same document would take the same
/// name, in which case `main` is `Main`.
fn type_name_for_def(corpus: &Corpus, nsid: &str, def: &str) -> String {
    let last = nsid.rsplit('.').next().unwrap_or(nsid).to_pascal_case();
    if def == "main" {
        let taken = corpus.get(nsid).is_some_and(|doc| {
            doc.defs
                .keys()
                .any(|k| k != "main" && k.to_pascal_case() == last)
        });
        if taken { "Main".to_owned() } else { last }
    } else {
        def.to_pascal_case()
    }
}

/// Full Rust path of a definition's type.
fn type_path(corpus: &Corpus, nsid: &str, def: &str) -> String {
    let mods: Vec<String> = nsid.split('.').map(module_name).collect();
    format!(
        "crate::generated::{}::{}",
        mods.join("::"),
        type_name_for_def(corpus, nsid, def)
    )
}

fn union_tag(nsid: &str, def: &str) -> String {
    if def == "main" {
        nsid.to_owned()
    } else {
        format!("{nsid}#{def}")
    }
}

struct Emitter<'a> {
    corpus: &'a Corpus,
    doc_id: &'a str,
    out: String,
    inline_names: BTreeSet<String>,
}

impl Emitter<'_> {
    fn doc(&mut self, doc: &pds_lexicon::model::LexiconDoc) -> Result<()> {
        let _ = writeln!(self.out, "/// Lexicon `{}`.", doc.id);
        let _ = writeln!(self.out, "pub const NSID: &str = \"{}\";\n", doc.id);
        for (name, def) in &doc.defs {
            let tname = type_name_for_def(self.corpus, &doc.id, name);
            match def {
                LexUserType::Record(r) => {
                    self.doc_comment(r.description.as_deref());
                    let _ = writeln!(self.out, "/// Record key type: `{}`.", r.key);
                    self.object_struct(&tname, r.record.object(), true)?;
                }
                LexUserType::Query(q) => {
                    self.doc_comment(q.description.as_deref());
                    self.params(q.parameters.as_ref())?;
                    self.body("Output", q.output.as_ref())?;
                    self.errors(&q.errors);
                }
                LexUserType::Procedure(p) => {
                    self.doc_comment(p.description.as_deref());
                    self.params(p.parameters.as_ref())?;
                    self.body("Input", p.input.as_ref())?;
                    self.body("Output", p.output.as_ref())?;
                    self.errors(&p.errors);
                }
                LexUserType::Subscription(s) => {
                    self.doc_comment(s.description.as_deref());
                    self.params(s.parameters.as_ref())?;
                    if let Some(m) = &s.message {
                        match &m.schema {
                            LexRefUnionOrUnion::Union(u) => self.union_enum("Message", u)?,
                            LexRefUnionOrUnion::Ref(r) => {
                                let target = self.ref_path(&r.ref_)?;
                                let _ = writeln!(
                                    self.out,
                                    "/// The message type.\npub type Message = {target};\n"
                                );
                            }
                        }
                    }
                    self.errors(&s.errors);
                }
                LexUserType::Object(o) => {
                    self.doc_comment(o.description.as_deref());
                    self.object_struct(&tname, o, false)?;
                }
                LexUserType::Union(u) => {
                    self.doc_comment(u.description.as_deref());
                    self.union_enum(&tname, u)?;
                }
                LexUserType::Token(t) => {
                    self.doc_comment(t.description.as_deref());
                    let const_name = name.to_snake_case().to_uppercase();
                    let _ = writeln!(
                        self.out,
                        "pub const {const_name}: &str = \"{}\";\n",
                        union_tag(&doc.id, name)
                    );
                }
                LexUserType::String(s) => {
                    self.doc_comment(s.description.as_deref());
                    let _ = writeln!(self.out, "pub type {tname} = {};\n", string_type(s));
                }
                LexUserType::Integer(i) => {
                    self.doc_comment(i.description.as_deref());
                    let _ = writeln!(self.out, "pub type {tname} = i64;\n");
                }
                LexUserType::Boolean(b) => {
                    self.doc_comment(b.description.as_deref());
                    let _ = writeln!(self.out, "pub type {tname} = bool;\n");
                }
                LexUserType::Bytes(b) => {
                    self.doc_comment(b.description.as_deref());
                    let _ = writeln!(self.out, "pub type {tname} = crate::data::Bytes;\n");
                }
                LexUserType::CidLink(c) => {
                    self.doc_comment(c.description.as_deref());
                    let _ = writeln!(self.out, "pub type {tname} = crate::data::CidLink;\n");
                }
                LexUserType::Blob(b) => {
                    self.doc_comment(b.description.as_deref());
                    let _ = writeln!(self.out, "pub type {tname} = crate::data::BlobRef;\n");
                }
                LexUserType::Array(a) => {
                    self.doc_comment(a.description.as_deref());
                    let item = self.type_of(&tname, "Item", &a.items)?;
                    let _ = writeln!(self.out, "pub type {tname} = Vec<{item}>;\n");
                }
                LexUserType::Unknown(u) => {
                    self.doc_comment(u.description.as_deref());
                    let _ = writeln!(self.out, "pub type {tname} = crate::data::Data;\n");
                }
                LexUserType::Ref(r) => {
                    let target = self.ref_path(&r.ref_)?;
                    let _ = writeln!(self.out, "pub type {tname} = {target};\n");
                }
                LexUserType::PermissionSet(p) => {
                    self.doc_comment(p.description.as_deref());
                    let _ = writeln!(
                        self.out,
                        "/// Permission set `{}`; resolved at runtime by pds-lexicon.\npub const PERMISSION_SET: &str = \"{}\";\n",
                        doc.id, doc.id
                    );
                }
                LexUserType::Permission(_) => {}
            }
        }
        Ok(())
    }

    fn doc_comment(&mut self, description: Option<&str>) {
        if let Some(d) = description {
            for line in d.lines() {
                let _ = writeln!(self.out, "/// {}", line.trim_end());
            }
        }
    }

    fn params(&mut self, params: Option<&LexXrpcParameters>) -> Result<()> {
        let Some(p) = params else { return Ok(()) };
        self.doc_comment(p.description.as_deref());
        let _ = writeln!(
            self.out,
            "#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]"
        );
        let _ = writeln!(self.out, "pub struct Params {{");
        for (name, prop) in &p.properties {
            let required = p.required.iter().any(|r| r == name);
            let ty = match prop {
                LexPrimitiveOrArray::String(s) => string_type(s),
                LexPrimitiveOrArray::Integer(_) => "i64".to_owned(),
                LexPrimitiveOrArray::Boolean(_) => "bool".to_owned(),
                LexPrimitiveOrArray::Array(a) => {
                    format!("Vec<{}>", self.type_of("Params", name, &a.items)?)
                }
                LexPrimitiveOrArray::Unknown(_) => "crate::data::Data".to_owned(),
            };
            let desc = match prop {
                LexPrimitiveOrArray::String(s) => s.description.clone(),
                LexPrimitiveOrArray::Integer(i) => i.description.clone(),
                LexPrimitiveOrArray::Boolean(b) => b.description.clone(),
                LexPrimitiveOrArray::Array(a) => a.description.clone(),
                LexPrimitiveOrArray::Unknown(u) => u.description.clone(),
            };
            self.field(name, &ty, required, false, desc.as_deref());
        }
        let _ = writeln!(self.out, "}}\n");
        Ok(())
    }

    fn body(&mut self, which: &str, body: Option<&LexXrpcBody>) -> Result<()> {
        let Some(b) = body else { return Ok(()) };
        self.doc_comment(b.description.as_deref());
        let _ = writeln!(self.out, "/// Encoding: `{}`.", b.encoding);
        match &b.schema {
            Some(LexObjectOrRef::Object(o)) => self.object_struct(which, o, false)?,
            Some(LexObjectOrRef::Ref(r)) => {
                let target = self.ref_path(&r.ref_)?;
                let _ = writeln!(self.out, "pub type {which} = {target};\n");
            }
            Some(LexObjectOrRef::Union(u)) => self.union_enum(which, u)?,
            None => {
                let _ = writeln!(self.out, "pub type {which} = Vec<u8>;\n");
            }
        }
        Ok(())
    }

    fn errors(&mut self, errors: &[LexXrpcError]) {
        let _ = writeln!(self.out, "/// Named errors this method may return.");
        let _ = write!(self.out, "pub const ERRORS: &[&str] = &[");
        for (i, e) in errors.iter().enumerate() {
            if i > 0 {
                self.out.push_str(", ");
            }
            let _ = write!(self.out, "\"{}\"", e.name);
        }
        self.out.push_str("];\n\n");
    }

    fn object_struct(&mut self, name: &str, obj: &LexObject, is_record: bool) -> Result<()> {
        let mut fields = String::new();
        for (fname, ftype) in &obj.properties {
            let required = obj.required.iter().any(|r| r == fname);
            let nullable = obj.nullable.iter().any(|r| r == fname);
            let ty = self.type_of(name, fname, ftype)?;
            let desc = type_description(ftype);
            let mut f = String::new();
            std::mem::swap(&mut self.out, &mut f);
            self.field(fname, &ty, required, nullable, desc.as_deref());
            std::mem::swap(&mut self.out, &mut f);
            fields.push_str(&f);
        }
        let _ = writeln!(
            self.out,
            "#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]"
        );
        let _ = writeln!(self.out, "pub struct {name} {{");
        if is_record {
            let _ = writeln!(
                self.out,
                "    /// The record type, present when stored in a repository."
            );
            let _ = writeln!(
                self.out,
                "    #[serde(rename = \"$type\", default, skip_serializing_if = \"Option::is_none\")]"
            );
            let _ = writeln!(self.out, "    pub type_: Option<String>,");
        }
        self.out.push_str(&fields);
        let _ = writeln!(self.out, "}}\n");
        Ok(())
    }

    fn field(&mut self, name: &str, ty: &str, required: bool, nullable: bool, desc: Option<&str>) {
        let (rust_name, renamed) = field_name(name);
        if let Some(d) = desc {
            for line in d.lines() {
                let _ = writeln!(self.out, "    /// {}", line.trim_end());
            }
        }
        let mut attrs = Vec::new();
        if renamed {
            attrs.push(format!("rename = \"{name}\""));
        }
        let field_ty = if required && !nullable {
            ty.to_owned()
        } else if required && nullable {
            format!("Option<{ty}>")
        } else {
            attrs.push("default".to_owned());
            attrs.push("skip_serializing_if = \"Option::is_none\"".to_owned());
            format!("Option<{ty}>")
        };
        if !attrs.is_empty() {
            let _ = writeln!(self.out, "    #[serde({})]", attrs.join(", "));
        }
        let _ = writeln!(self.out, "    pub {rust_name}: {field_ty},");
    }

    fn union_enum(&mut self, name: &str, u: &LexRefUnion) -> Result<()> {
        let closed = u.closed.unwrap_or(false);
        let _ = writeln!(
            self.out,
            "#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]"
        );
        let _ = writeln!(self.out, "#[serde(tag = \"$type\")]");
        let _ = writeln!(self.out, "pub enum {name} {{");
        let mut used = BTreeSet::new();
        for r in &u.refs {
            let (nsid, def) = self.resolve(r)?;
            let path = type_path(self.corpus, &nsid, &def);
            let tag = union_tag(&nsid, &def);
            let mut variant = variant_name(&nsid, &def);
            let mut n = 2;
            while !used.insert(variant.clone()) {
                variant = format!("{}{n}", variant_name(&nsid, &def));
                n += 1;
            }
            let _ = writeln!(self.out, "    #[serde(rename = \"{tag}\")]");
            let _ = writeln!(self.out, "    {variant}(Box<{path}>),");
        }
        if !closed {
            let _ = writeln!(
                self.out,
                "    /// A member outside the listed references (open union)."
            );
            let _ = writeln!(self.out, "    #[serde(untagged)]");
            let _ = writeln!(self.out, "    Other(crate::data::Data),");
        }
        let _ = writeln!(self.out, "}}\n");
        Ok(())
    }

    /// The Rust type for a property, generating inline objects and unions
    /// as named items in the current module.
    fn type_of(&mut self, parent: &str, field: &str, t: &LexType) -> Result<String> {
        Ok(match t {
            LexType::String(s) => string_type(s),
            LexType::Integer(_) => "i64".to_owned(),
            LexType::Boolean(_) => "bool".to_owned(),
            LexType::Bytes(_) => "crate::data::Bytes".to_owned(),
            LexType::CidLink(_) => "crate::data::CidLink".to_owned(),
            LexType::Blob(_) => "crate::data::BlobRef".to_owned(),
            LexType::Unknown(_) => "crate::data::Data".to_owned(),
            LexType::Array(a) => format!("Vec<{}>", self.array_item(parent, field, a)?),
            LexType::Ref(r) => self.ref_path(&r.ref_)?,
            LexType::Union(u) => {
                let name = self.inline_name(parent, field);
                self.union_enum(&name, u)?;
                name
            }
            LexType::Object(o) => {
                let name = self.inline_name(parent, field);
                self.object_struct(&name, o, false)?;
                name
            }
        })
    }

    fn array_item(&mut self, parent: &str, field: &str, a: &LexArray) -> Result<String> {
        self.type_of(parent, &format!("{field}Item"), &a.items)
    }

    fn inline_name(&mut self, parent: &str, field: &str) -> String {
        let base = format!(
            "{}{}",
            parent.trim_start_matches("r#").to_pascal_case(),
            field.to_pascal_case()
        );
        let mut name = base.clone();
        let mut n = 2;
        while !self.inline_names.insert(name.clone()) {
            name = format!("{base}{n}");
            n += 1;
        }
        name
    }

    fn resolve(&self, reference: &str) -> Result<(String, String)> {
        let (nsid, def) = match reference.split_once('#') {
            Some(("", def)) => (self.doc_id, def),
            Some((nsid, def)) => (nsid, def),
            None => (reference, "main"),
        };
        self.corpus
            .resolve_ref(self.doc_id, reference)
            .with_context(|| format!("{}: unresolved reference {reference}", self.doc_id))?;
        Ok((nsid.to_owned(), def.to_owned()))
    }

    fn ref_path(&self, reference: &str) -> Result<String> {
        let (nsid, def) = self.resolve(reference)?;
        let doc = self.corpus.get(&nsid).context("resolved document exists")?;
        match doc.defs.get(&def) {
            Some(LexUserType::Token(_)) => Ok("String".to_owned()),
            Some(
                LexUserType::Query(_) | LexUserType::Procedure(_) | LexUserType::Subscription(_),
            ) => {
                bail!(
                    "{}: reference {reference} points at an XRPC method",
                    self.doc_id
                )
            }
            Some(_) => Ok(type_path(self.corpus, &nsid, &def)),
            None => bail!("{}: unresolved reference {reference}", self.doc_id),
        }
    }
}

fn variant_name(nsid: &str, def: &str) -> String {
    let last = nsid.rsplit('.').next().unwrap_or(nsid).to_pascal_case();
    if def == "main" {
        last
    } else {
        format!("{last}{}", def.to_pascal_case())
    }
}

fn string_type(s: &LexString) -> String {
    match s.format.as_deref() {
        Some("did") => "crate::syntax::Did",
        Some("handle") => "crate::syntax::Handle",
        Some("nsid") => "crate::syntax::Nsid",
        Some("at-uri") => "crate::syntax::AtUri",
        Some("at-identifier") => "crate::syntax::AtIdentifier",
        Some("cid") => "crate::syntax::CidString",
        Some("datetime") => "crate::syntax::Datetime",
        Some("tid") => "crate::syntax::Tid",
        Some("record-key") => "crate::syntax::RecordKey",
        Some("language") => "crate::syntax::Language",
        Some("uri") => "crate::syntax::Uri",
        _ => "String",
    }
    .to_owned()
}

fn type_description(t: &LexType) -> Option<String> {
    match t {
        LexType::String(s) => s.description.clone(),
        LexType::Integer(i) => i.description.clone(),
        LexType::Boolean(b) => b.description.clone(),
        LexType::Bytes(b) => b.description.clone(),
        LexType::CidLink(c) => c.description.clone(),
        LexType::Blob(b) => b.description.clone(),
        LexType::Array(a) => a.description.clone(),
        LexType::Object(o) => o.description.clone(),
        LexType::Ref(r) => r.description.clone(),
        LexType::Union(u) => u.description.clone(),
        LexType::Unknown(u) => u.description.clone(),
    }
}
